autoInstallPeers: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - 'esbuild'
  - 'nx'
  - 'sharp'
onlyBuiltDependencies:
  - 'less'
  - 'unrs-resolver'
packages:
  - 'apps/*'
  - 'libs/**'
  - 'shared/*'
  - 'bunkers/*'
  - 'shared-fundamentals/*'
  - 'modular-units/*'
